---
- hosts: master_root 
  become: true

  tasks:
    - name: Initialize Kubernetes master
      command: kubeadm init --apiserver-advertise-address=10.1.0.11 --pod-network-cidr=10.1.0.0/16

    - name: Set up kubeconfig for the user
      command: "{{ item }}"
      with_items:
        - mkdir -p $HOME/.kube
        - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

    - name: Install Flannel network plugin
      command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
