# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "kubemaster1" do |node|
    node.vm.hostname = "kubemaster1.internal"
    node.vm.network "private_network", ip: "10.1.0.11"

    node.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
    end
  end

  (1..2).each do |j|
    config.vm.define "kubenode#{j}" do |node|
      node.vm.hostname = "kubenode#{j}.internal"
      node.vm.network "private_network", ip: "10.1.0.2#{j}"

      node.vm.provider :libvirt do |domain|
        domain.memory = 1024
        domain.cpus = 1
      end
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.groups = {
      "kubernetes" => ["kubemaster1", "kubenode1", "kubenode2"], 
      "master_root" => ["kubemaster1"],
      "workers" => ["kubenode1", "kubenode2"],
    }
  end
end
